---
- name: turn off ugly iptables
  service: name=iptables state=stopped
  tags:
  - vagrant

- name: make terminal pretty with a better .bash_profile
  template: src=bash_profile.j2 dest="/home/vagrant/.bash_profile"
  tags:
  - installation
