---
- name: composer install
  shell: /usr/local/bin/composer install chdir={{app.sites[0]['path']}}

- name: composer update
  shell: /usr/local/bin/composer update chdir={{app.sites[0]['path']}}

- name: composer dump
  shell: /usr/local/bin/composer dump-autoload chdir={{app.sites[0]['path']}}

- name: artisan dump
  shell: php artisan dump-autoload chdir={{app.sites[0]['path']}}

- name: db migrate
  shell: php artisan migrate chdir={{app.sites[0]['path']}}

- name: db refresh
  shell: php artisan migrate:refresh chdir={{app.sites[0]['path']}}

- name: db seed
  shell: php artisan db:seed chdir={{app.sites[0]['path']}}
